from typing import List

from python.utils.globals import MIN_VEHICLE_ID

vehicle_names: List[str] = ['Landstalker',
                            'Bravura',
                            'Buffalo',
                            'Linerunner',
                            'Perennial',
                            'Sentinel',
                            'Dumper',
                            'Fire Truck',
                            'Trashmaster',
                            'Stretch',
                            'Manana',
                            'Infernus',
                            'Voodoo',
                            'Pony',
                            'Mule',
                            'Cheetah',
                            'Ambulance',
                            'Leviathan',
                            'Moonbeam',
                            'Esperanto',
                            'Taxi',
                            'Washington',
                            'Bobcat',
                            'Mr. Whoopee',
                            'BF Injection',
                            'Hunter',
                            'Premier',
                            'Enforcer',
                            'Securicar',
                            'Banshee',
                            'Predator',
                            'Bus',
                            'Rhino',
                            'Barracks',
                            'Hotknife',
                            'ARTICT1',
                            'Previon',
                            'Coach',
                            'Cabbie',
                            'Stallion',
                            'Rumpo',
                            'RC Bandit',
                            'Romero',
                            'Packer',
                            'Monster',
                            'Admiral',
                            'Squalo',
                            'Seasparrow',
                            'Pizzaboy',
                            'Tram',
                            'ARTICT2',
                            'Turismo',
                            'Speeder',
                            'Reefer',
                            'Tropic',
                            'Flatbed',
                            'Yankee',
                            'Caddy',
                            'Solair',
                            'Berkleys RC Van',
                            'Skimmer',
                            'PCJ-600',
                            'Faggio',
                            'Freeway',
                            'RC Baron',
                            'RC Raider',
                            'Glendale',
                            'Oceanic',
                            'Sanchez',
                            'Sparrow',
                            'Patriot',
                            'Quadbike',
                            'Coastguard',
                            'Dinghy',
                            'Hermes',
                            'Sabre',
                            'Rustler',
                            'ZR-350',
                            'Walton',
                            'Regina',
                            'Comet',
                            'BMX',
                            'Burrito',
                            'Camper',
                            'Marquis',
                            'Baggage',
                            'Dozer',
                            'Maverick',
                            'News Chopper',
                            'Rancher',
                            'FBI Rancher',
                            'Virgo',
                            'Greenwood',
                            'Jetmax',
                            'Hotring Racer',
                            'Sandking',
                            'Blista Compact',
                            'Police Maverick',
                            'Boxville',
                            'Benson',
                            'Mesa',
                            'RC Goblin',
                            'Hotring Racer',
                            'Hotring Racer',
                            'Bloodring Banger',
                            'Rancher',
                            'Super GT',
                            'Elegant',
                            'Journey',
                            'Bike',
                            'Mountain Bike',
                            'Beagle',
                            'Cropduster',
                            'Stuntplane',
                            'Tanker',
                            'Roadtrain',
                            'Nebula',
                            'Majestic',
                            'Buccaneer',
                            'Shamal',
                            'Hydra',
                            'FCR-900',
                            'NRG-500',
                            'HPV1000',
                            'Cement Truck',
                            'Towtruck',
                            'Fortune',
                            'Cadrona',
                            'FBI Truck',
                            'Willard',
                            'Forklift',
                            'Tractor',
                            'Combine Harvester',
                            'Feltzer',
                            'Remington',
                            'Slamvan',
                            'Blade',
                            'Freight',
                            'Brown Streak',
                            'Vortex',
                            'Vincent',
                            'Bullet',
                            'Clover',
                            'Sadler',
                            'Fire Truck',
                            'Hustler',
                            'Intruder',
                            'Primo',
                            'Cargobob',
                            'Tampa',
                            'Sunrise',
                            'Merit',
                            'Utility Van',
                            'Nevada',
                            'Yosemite',
                            'Windsor',
                            'Monster',
                            'Monster',
                            'Uranus',
                            'Jester',
                            'Sultan',
                            'Stratum',
                            'Elegy',
                            'Raindance',
                            'RC Tiger',
                            'Flash',
                            'Tahoma',
                            'Savanna',
                            'Bandito',
                            'Freight',
                            'Brown Streak',
                            'Kart',
                            'Mower',
                            'Dune',
                            'Sweeper',
                            'Broadway',
                            'Tornado',
                            'AT-400',
                            'DFT-30',
                            'Huntley',
                            'Stafford',
                            'BF-400',
                            'Newsvan',
                            'Tug',
                            'Petrol Truck',
                            'Emperor',
                            'Wayfarer',
                            'Euros',
                            'Hotdog',
                            'Club',
                            'FRBOX',
                            'ARTICT3',
                            'Andromada',
                            'Dodo',
                            'RC Cam',
                            'Launch',
                            'Police',
                            'Police',
                            'Police',
                            'Ranger',
                            'Picador',
                            'S.W.A.T.',
                            'Alpha',
                            'Phoenix',
                            'Glendale',
                            'Sadler',
                            'BAGBOXA',
                            'BAGBOXB',
                            'TUGSTAI',
                            'Boxville',
                            'FARMTR1',
                            'UTILTR1']

vehicle_model_names: List[str] = ['landstal',
                                  'bravura',
                                  'buffalo',
                                  'linerun',
                                  'peren',
                                  'sentinel',
                                  'dumper',
                                  'firetruk',
                                  'trash',
                                  'stretch',
                                  'manana',
                                  'infernus',
                                  'voodoo',
                                  'pony',
                                  'mule',
                                  'cheetah',
                                  'ambulan',
                                  'leviathn',
                                  'moonbeam',
                                  'esperant',
                                  'taxi',
                                  'washing',
                                  'bobcat',
                                  'mrwhoop',
                                  'bfinject',
                                  'hunter',
                                  'premier',
                                  'enforcer',
                                  'securica',
                                  'banshee',
                                  'predator',
                                  'bus',
                                  'rhino',
                                  'barracks',
                                  'hotknife',
                                  'artict1',
                                  'previon',
                                  'coach',
                                  'cabbie',
                                  'stallion',
                                  'rumpo',
                                  'rcbandit',
                                  'romero',
                                  'packer',
                                  'monster',
                                  'admiral',
                                  'squalo',
                                  'seaspar',
                                  'pizzaboy',
                                  'tram',
                                  'artict2',
                                  'turismo',
                                  'speeder',
                                  'reefer',
                                  'tropic',
                                  'flatbed',
                                  'yankee',
                                  'caddy',
                                  'solair',
                                  'topfun',
                                  'skimmer',
                                  'pcj600',
                                  'faggio',
                                  'freeway',
                                  'rcbaron',
                                  'rcraider',
                                  'glendale',
                                  'oceanic',
                                  'sanchez',
                                  'sparrow',
                                  'patriot',
                                  'quad',
                                  'coastg',
                                  'dinghy',
                                  'hermes',
                                  'sabre',
                                  'rustler',
                                  'zr350',
                                  'walton',
                                  'regina',
                                  'comet',
                                  'bmx',
                                  'burrito',
                                  'camper',
                                  'marquis',
                                  'baggage',
                                  'dozer',
                                  'maverick',
                                  'vcnmav',
                                  'rancher',
                                  'fbiranch',
                                  'virgo',
                                  'greenwoo',
                                  'jetmax',
                                  'hotring',
                                  'sandking',
                                  'blistac',
                                  'polmav',
                                  'boxville',
                                  'benson',
                                  'mesa',
                                  'rcgoblin',
                                  'hotrina',
                                  'hotrinb',
                                  'bloodra',
                                  'rnchlure',
                                  'supergt',
                                  'elegant',
                                  'journey',
                                  'bike',
                                  'mtbike',
                                  'beagle',
                                  'cropdust',
                                  'stunt',
                                  'petro',
                                  'rdtrain',
                                  'nebula',
                                  'majestic',
                                  'buccanee',
                                  'shamal',
                                  'hydra',
                                  'fcr900',
                                  'nrg500',
                                  'copbike',
                                  'cement',
                                  'towtruck',
                                  'fortune',
                                  'cadrona',
                                  'fbitruck',
                                  'willard',
                                  'forklift',
                                  'tractor',
                                  'combine',
                                  'feltzer',
                                  'remingtn',
                                  'slamvan',
                                  'blade',
                                  'freight',
                                  'streak',
                                  'vortex',
                                  'vincent',
                                  'bullet',
                                  'clover',
                                  'sadler',
                                  'firela',
                                  'hustler',
                                  'intruder',
                                  'primo',
                                  'cargobob',
                                  'tampa',
                                  'sunrise',
                                  'merit',
                                  'utility',
                                  'nevada',
                                  'yosemite',
                                  'windsor',
                                  'monstera',
                                  'monsterb',
                                  'uranus',
                                  'jester',
                                  'sultan',
                                  'stratum',
                                  'elegy',
                                  'raindanc',
                                  'rctiger',
                                  'flash',
                                  'tahoma',
                                  'savanna',
                                  'bandito',
                                  'freiflat',
                                  'streakc',
                                  'kart',
                                  'mower',
                                  'duneride',
                                  'sweeper',
                                  'broadway',
                                  'tornado',
                                  'at400',
                                  'dft30',
                                  'huntley',
                                  'stafford',
                                  'bf400',
                                  'newsvan',
                                  'tug',
                                  'petrotr',
                                  'emperor',
                                  'wayfarer',
                                  'euros',
                                  'hotdog',
                                  'club',
                                  'freibox',
                                  'artict3',
                                  'androm',
                                  'dodo',
                                  'rccam',
                                  'launch',
                                  'copcarla',
                                  'copcarsf',
                                  'copcarvg',
                                  'copcarru',
                                  'picador',
                                  'swatvan',
                                  'alpha',
                                  'phoenix',
                                  'glenshit',
                                  'sadlshit',
                                  'bagboxa',
                                  'bagboxb',
                                  'tugstair',
                                  'boxburg',
                                  'farmtr1',
                                  'utiltr1']


def get_model_id_by_name(name: str) -> int | None:
    for i in range(len(vehicle_names)):
        if name in vehicle_names[i].lower():
            return i + MIN_VEHICLE_ID

    return None
